package org.eclipse.tractusx.demandcapacitymgmt.demandcapacitymgmtbackend.entities;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Entity
@Table(name = "DEMAND")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DemandEntity {

    @Id
    @Column(name = "ID", nullable = false)
    private Integer id;

    @ManyToOne
    @JoinColumn(name = "PROJECT_ID", referencedColumnName = "ID")
    private ProjectEntity project;

    @ManyToOne
    @JoinColumn(name = "SUPPLIER_ID", referencedColumnName = "ID")
    private SupplierEntity supplier;

    @Column(name = "REQUIRED_CAPACITY")
    private Double requiredCapacity;

    @Column(name = "ACTUAL_DEMAND")
    private Double actualDemand;

    @Column(name = "DESCRIPTION")
    private String description;

    // Getters and setters are automatically generated by Lombok

}
