openapi: '3.0.2'
info:
  title: Spring Template API
  version: '1.0'
servers:
  - url: https://localhost:8080/api/v1

paths:
  /hello-open:
    get:
      summary: return a simple generic greeting
      operationId: getGreeting
      responses:
        200:
          description: General greeting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'
components:
  schemas:
    Greeting:
      type: object
      properties:
        message:
          type: string
          example: 'Hello from Spring'
          default: 'Hello visitor'